run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gocyclo
    - path: vendor/
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0
